[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version = "0.22.0", features = ["ssr"] }
rusttype = "0.9.3"
resvg = "0.47.0"
usvg = "0.47.0"
tiny-skia = "0.12.0"
once_cell = "1.21.3"

[lib]
crate-type = ["cdylib", "rlib"]
